export const categories = [
    { name: 'Groceries', image: 'groceries' },
    { name: 'Rent', image: 'rent' },
    { name: 'Netflix', image: 'netflix' },
    { name: 'Amazon', image: 'amazon' },
    { name: 'Spotify', image: 'spotify' },
    { name: 'Amazon Prime', image: 'amazon_prime' },
    { name: 'Hulu', image: 'hulu' },
    { name: 'Disney+', image: 'disney_plus' },
    { name: 'HBO Max', image: 'hbo_max' },
    { name: 'Apple Music', image: 'apple_music' },
    { name: 'YouTube Premium', image: 'youtube_premium' },
    { name: 'Utilities', image: 'utilities' },
    { name: 'Transportation', image: 'transportation' },
    { name: 'Dining Out', image: 'dining_out' },
    { name: 'Gym', image: 'gym' },
    { name: 'Insurance', image: 'insurance' },
    { name: 'Phone', image: 'phone' },
    { name: 'Internet', image: 'internet' },
    { name: 'Clothing', image: 'clothing' },
    { name: 'Healthcare', image: 'healthcare' },
    { name: 'Education', image: 'education' },
    { name: 'Entertainment', image: 'entertainment' },
    { name: 'Travel', image: 'travel' },
    { name: 'Savings', image: 'savings' },
    { name: 'Investments', image: 'investments' },
    { name: 'Pets', image: 'pets' },
    { name: 'Hobbies', image: 'hobbies' },
    { name: 'Gifts', image: 'gifts' },
    { name: 'Charity', image: 'charity' },
    { name: 'Loans', image: 'loans' },
    { name: 'Credit Card', image: 'credit_card' },
    { name: 'Household Supplies', image: 'household_supplies' },
    { name: 'Childcare', image: 'childcare' },
    { name: 'Subscriptions', image: 'subscriptions' },
    { name: 'Self-Care', image: 'self_care' },
    { name: 'Shopping', image: 'shopping' },
    { name: 'Work Expenses', image: 'work_expenses' },
    { name: 'Car Maintenance', image: 'car_maintenance' },
    { name: 'Home Maintenance', image: 'home_maintenance' },
    { name: 'Alcohol', image: 'alcohol' },
    { name: 'Cigarettes', image: 'cigarettes' },
    { name: 'Laundry', image: 'laundry' },
    { name: 'Pharmacy', image: 'pharmacy' },
    { name: 'Beauty', image: 'beauty' },
    { name: 'Books', image: 'books' },
    { name: 'Games', image: 'games' },
    { name: 'Music', image: 'music' },
    { name: 'Movies', image: 'movies' },
    { name: 'Tech Gadgets', image: 'tech_gadgets' },
    { name: 'Office Supplies', image: 'office_supplies' },
    { name: 'Memberships', image: 'memberships' },
    { name: 'Fitness', image: 'fitness' },
    { name: 'Festivals', image: 'festivals' },
    { name: 'Events', image: 'events' },
    { name: 'Miscellaneous', image: 'miscellaneous' },
    { name: 'Microsoft 365', image: 'microsoft_365' },
    { name: 'Adobe Creative Cloud', image: 'adobe_creative_cloud' },
    { name: 'Dropbox', image: 'dropbox' },
    { name: 'Slack', image: 'slack' },
    { name: 'Zoom', image: 'zoom' },
    { name: 'Patreon', image: 'patreon' },
    { name: 'Google One', image: 'google_one' }
];
